@echo off
mode 800

echo YOU HAVE BEEN HACKED

:A
color 0c
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! YOU HAVE BEEN HACKED
echo WARNING! VIRUS DETECTED
echo WARNING! VIRUS DETECTED
echo WARNING! VIRUS DETECTED
echo WARNING! VIRUS DETECTED
timeout /T 4
color 02
:start 
echo %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random%
GOTO start